Implementação função PSTORE
hayelleon/munchkin_game pull request #11
Opened 2018-11-04 18:27 UTC by hayelleon

Tá PStoradinho.. IWTS

2018-11-04 21:09 UTC, khamusa requested changes
Ainda tenho mais alterações a sugerir, mas vou esperar  você rever estas.

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  munchkin_rooms = PStore.new("munchkin_rooms.pstore")
lembre de usar aspas simples quando não precisar da interpolação

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  munchkin_rooms[:munchkin_room] = munchkin_room.to_json
esta linha precisa estar indentada, pois está dentro do bloco `do ... end`

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  json munchkin_room = {
Por convenção, quando desenvolvemos serviços web, a última instrução deve ser a que gera o resultado para o navegador. Portanto, a chamada de `json` deve ficar lá no final, por último.

Também não é boa prática definir uma variável e passar o resultado da definição como parâmetro de um método. Ao invés de:
```ruby
meu_metodo minha_variavel = 123
meu_array.push(minha_variavel)
```
é preferível
```ruby
minha_variavel = 123
meu_metodo minha_variável
meu_array.push(minha_variavel)
```

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  munchkin_rooms.transaction do
isso aqui pode ficar antes da renderização de json.
Então seu código fica nessa ordem:
1) definir variável `munchkin_room`
2) salvar no pstore
3) renderizar o json

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  munchkin_rooms = PStore.new("munchkin_rooms.pstore")
para melhorar a organização dos arquivos, salve os arquivos .pstore em uma subpasta. Pode se chamar `data` ou `storage`. Ou, se preferir em pt, `dados`

2018-11-04 21:09 UTC, khamusa commented on cadastro.rb
> +  munchkin_rooms[:munchkin_room] = munchkin_room.to_json
Sobre a escolha de nome para as variáveis:
como estamos em um app sobre munchkin, essa já é uma informação contida no projeto em si. 
Eu sugeriria usar:
- `created_room` para a sala sendo criada agora
- `room_storage` para a variável que contém a instância do pstore que usamos para salvar.

2018-11-04 21:30 UTC, hayelleon commented on cadastro.rb
> +  json munchkin_room = {
Eu entendi mas não compreendi!
Depois me explica com calma, pls!

2018-11-04 22:03 UTC, khamusa requested changes

2018-11-04 22:03 UTC, khamusa commented on cadastro.rb
> +    room_storage[:munchkin_room] = room_storage.to_json
aqui está errado. Estamos salvando a própria storage dentro dela mesma?

2018-11-04 22:03 UTC, khamusa commented on cadastro.rb
> +    room_storage[:munchkin_room] = room_storage.to_json
Queremos salvar apenas as informações sobre a sala criada. As informações da sala criada são apenas seu uuid e seu name, nada mais

2018-11-04 22:03 UTC, khamusa commented on cadastro.rb
> +  status: 'created',
a indentação desta hash não está correta

2018-11-04 22:03 UTC, khamusa commented on cadastro.rb
> +  room_storage = PStore.new('pt/dados/munchkin_rooms.pstore')
acho que não precisa da pasta 'pt'. Os dados armazenados não dependem do idioma. Quando falei que se vc preferir 'pt' poderia ser "dados" me referia apenas a usar a palavra "dados" ao invés de "data"

2018-11-05 19:41 UTC, khamusa requested changes

2018-11-05 19:41 UTC, khamusa commented on cadastro.rb
> +  puts room_storage.to_s
vamos remover essa linha aqui

2018-11-05 19:41 UTC, khamusa commented on cadastro.rb
> +    room_storage[:uuid] = munchkin_room[:uuid]
perfeito, a ideia é essa. Contudo, ao invés de salvar apenas uma sala, queremos salvar um array de salas.
Então seria algo mais ou menos assim:
```ruby
# salvamos em um hash a sala criada
muchkin_room = {
  uuid: created_room.uud,
  name: created_room.name
}

room_storage.transaction do
 
  room_storage[:rooms] ||= [] # se o array não existe, garantimos que exista um array vazio
  room_storage[:rooms].push(muchkin_room) # adicionamos o hash da sala criada no array
end

# renderizamos
json(
  status: 'created',
  server_time: Time.now,
  data: munchkin_room # reutilizamos o mesmo hash que usamos para salvar, na renderização
)
```

com isso, a cada sala que criamos, salvamos adicionamos ela à um array de salas

2018-11-07 02:03 UTC, khamusa commented on cadastro.rb
> +    room_storage[:rooms].push(munchkin_room)
Está ótimo. Quero chamar a atenção para o fato de que não fizemos `munchkin_room.json` aqui. O PStore nos permite salvar objetos ruby diretamente, portanto não precisamos converter em json. A conversão em json serve para salvar objetos ruby como string. Se, ao invés de usar PStore, quiséssemos usar `File`, poderíamos usar a conversão em json para salvar em um arquivo de texto.

Ótimo trabalho!

2018-11-07 02:03 UTC, merged